# fly.toml app configuration file generated for mango-discord-bot on 2023-05-22T18:58:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mango-discord-bot"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[mounts]
  source="mango_discord_bot_state"
  destination="./app/state"
