version: "3.9"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      WORLD: "./minecraft-world/world"
      DIFFICULTY: "hard"
      MODE: "creative" # creative, survival, adventure, spectator 
      MAX_PLAYERS: "20"
      VIEW_DISTANCE: "25"
      SIMULATION_DISTANCE: "25"
      # SEED: "1785852800490497919" # Remove later
      MOTD: "Welcome to my Server" # Server Message
      TYPE: "VANILLA"
      OPS: "TheBlackMango__"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "false"
      TZ: "Europe/London" # Time zone
      LOG_TIMESTAMP: "true"
      ICON: "https://static.wikia.nocookie.net/hunterxhunter/images/8/88/Isaac_Netero_HE_Portrait.png" # Server Icon
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true