version: "3.9"

services:
  mc-server:
    image: itzg/minecraft-server:latest
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      WORLD: "./data/world"
      DIFFICULTY: "hard"
      MODE: "survival" # creative, survival, adventure, spectator 
      MAX_PLAYERS: "20"
      VIEW_DISTANCE: "27"
      SIMULATION_DISTANCE: "25"
      MOTD: "Mango Minecraft Server" # Server Message
      TYPE: "VANILLA"
      OPS: "TheBlackMango__"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "false"
      TZ: "Europe/London" # Time zone
      LOG_TIMESTAMP: "true"
      ICON: "xxICONxx" # Server Icon
    tty: true
    stdin_open: true
    restart: unless-stopped

  mc-monitoring:
    image: python:3.10-slim
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "pip install -r requirements.txt && python monitoring.py"
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
volumes:
  minecraftdata:
    external: true