name: CD Discord Bot

on:
  push:
    branches:
      - main
    paths:
      - "discord_bot/**"

env:
  GIT_TAG_PREFIX: "SMB" # SMB means Server Management Bot
  
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
        
      - name: Initialize Terraform Env
        working-directory: ./terraform/infrastructure_handler
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform init
          echo "API_URL=$(terraform output -raw api_gateway_url)" >> $GITHUB_ENV
      
      - name: Set up FLY CTL
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Discord Bot
        working-directory: discord_bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  
        run: |
          flyctl secrets set API_URL=${{ env.API_URL }}
          flyctl deploy --remote-only

      - name: Tag Git
        run: |
          latest_tag=$(git tag | grep '^${{ env.GIT_TAG_PREFIX }}_' | sort -t. -k1,1n -k2,2n -k3,3n | tail -n1)
          if [[ -z "$latest_tag" ]]; then
            echo "No tags found starting with ${{ env.GIT_TAG_PREFIX }}_"
            exit 1
          fi
  
          # Remove the prefix from the tag
          version_string=${latest_tag#${{ env.GIT_TAG_PREFIX }}_}
  
          # Split the version string into an array
          version=(${version_string//./ })
  
          # Increment patch version
          version[2]=$((version[2] + 1))
  
          # Construct new tag
          SMB_TAG="${{ env.GIT_TAG_PREFIX }}_${version[0]}.${version[1]}.${version[2]}"
  
          echo "New tag is $SMB_TAG"
  
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "$SMB_TAG"
          git push https://dark-mango-bot:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git --tags
        