name: CD Discord Bot

on:
  push:
    branches:
      - main
    paths:
      - "discord_bot/**"
  
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
        
      - name: Initialize Terraform Env
        working-directory: ./terraform/infrastructure_handler
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform init

          # Get Terraform outputs
          API_URL=$(terraform output -raw api_gateway_url)
          SERVER_IP=$(terraform output -raw eip)

          # Create Env Vars
          echo "API_URL=$API_URL" >> $GITHUB_ENV
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV

          # Hide the Environment Variables
          echo "::add-mask::$API_URL"
          echo "::add-mask::$SERVER_IP"
      
      - name: Set up FLY CTL
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Discord Bot
        working-directory: discord_bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  
        run: |
          flyctl secrets set API_URL=${{ env.API_URL }}
          flyctl secrets set SERVER_IP=${{ env.SERVER_IP }}
          flyctl secrets set DEV_DISCORD_ACCOUNT_ID=${{ secrets.DEV_DISCORD_ACCOUNT_ID }}
          flyctl deploy --remote-only

  git-tag:
    uses: Klyde-Moradeyo/minecraft-AWS-server/.github/workflows/reusable-git-tag.yml@github_workflows
    needs: deploy
    with:
      git_tag_prefix: "SMB" # SMB means Server Management Bot
    secrets:
      gh_pat_token: ${{ secrets.GH_PAT }}
        