# Doc: https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
name: CI/CD Infra handler

on:
  push:
    branches:
      - main
    paths:
      - "terraform/infrastructure_handler/**"
      - "lambda_function/**"
      - "fargate_task/**"
env:
  TF_CLOUD_ORGANIZATION: "mango-dev"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "minecraft-infra-handler"
  CONFIG_DIRECTORY: "./terraform/infrastructure_handler"
  GIT_TAG_PREFIX: "MCI" # MCI means Minecraft Infrastructure Coordinator

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      lambda: ${{ steps.filter.outputs.lambda }}
      terraform: ${{ steps.filter.outputs.terraform }}
      fargate: ${{ steps.filter.outputs.fargate }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lambda:
              - 'lambda_function/**'
            terraform:
              - 'terraform/infrastructure_handler/**'
            fargate:
              - 'fargate_task/**'

  ci-lambda:
    uses: ./.github/workflows/reusable-ci-lambda_func.yml
    needs: filter
    with:
      filter: ${{ needs.filter.outputs.lambda }}
    secrets:
      gh_pat_token: ${{ secrets.GH_PAT }}

  ci-fargate:
    uses: ./.github/workflows/reusable-ci-fargate-task.yml
    needs: filter
    with:
      filter: ${{ needs.filter.outputs.fargate }}
    secrets:
      gh_pat_token: ${{ secrets.GH_PAT }}
      aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      tf_api_token: ${{ secrets.TF_API_TOKEN }}

  cd-terraform-apply:
    needs: [ ci-fargate, ci-lambda ]
    uses: ./.github/workflows/reusable-cd-terraform-apply.yml
    with:
      tf_workspace: "minecraft-infra-handler"
      tf_cloud_org: "mango-dev"
      config_dir: "./terraform/infrastructure_handler"
    secrets:
      gh_pat_token: ${{ secrets.GH_PAT }}
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
